version: "3.0"
services:
  docker-1:
    image: botcity/botcity-python-web-firefox
    command: BotRunner
    env_file:
      - .env
    environment:
        SERVER: ${SERVER}
        LOGIN: ${LOGIN}
        KEY: ${KEY}
        MACHINE_ID: RUNNER_ALPHA
  docker-2:
    image: botcity/botcity-python-web-firefox
    command: BotRunner
    env_file:
      - .env
    environment:
        SERVER: ${SERVER}
        LOGIN: ${LOGIN}
        KEY:  ${KEY}
        MACHINE_ID: RUNNER_BETA
  docker-3:
    image: botcity/botcity-python-web-firefox
    command: BotRunner
    env_file:
      - .env
    environment:
        SERVER: ${SERVER}
        LOGIN: ${LOGIN}
        KEY:  ${KEY}
        MACHINE_ID: RUNNER_GAMA